### PR TITLE
Test DOKKU with same version as DDS.

### PR DESCRIPTION
**Pull request by tarzzz**
Part of https://github.com/plotly/streambed/issues/14217

This PR updates travis config to test dokku-acl with the same version as being used in DDS (DDS PR: https://github.com/plotly/dash-deployment-server/pull/712)

### CODE REVIEW

**Comment by tarzzz** [comment]
@BRONSOLO Please review.

**Review by BRONSOLO — APPROVED** [review]
:dancer:

**Comment by tarzzz** [comment]
@BRONSOLO I have updated it to `0.20.1` since that's what we use in DDS now. Please review.

**Review by BRONSOLO — APPROVED** [review]
:dancer:

**Comment by tarzzz** [comment]
The test passed, but the status check is not being sent to GitHub up for some reason:

image


Seems like travis' issue. I am going to merge this PR and we can investigate it more if that happens in future.

**Pull request merged**
